// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccdgujocscdetzjqqoik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZGd1am9jc2NkZXR6anFxb2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMzE2MTEsImV4cCI6MjA3NTgwNzYxMX0.Wq1cYlq38JyF11G1lJb0wU59RV5qkJyyNhy2hyJWTos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});